spring.application.name=Inventory stock control system
spring.datasource.url = jdbc:postgresql://localhost:5432/ics
spring.datasource.username = admin
spring.datasource.password = secret
spring.jpa.hibernate.ddl-auto = validate
spring.jpa.show-sql = true

jwt.secret =aVeryLongSecureSecretKeyThatIsAtLeast64CharactersLongForHS256OK!! 
jwt.expiration = 86400000
